# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "virtio_pci" "xhci_pci" "usbhid" "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5a387e47-22ae-4e1d-81da-b9ac913a48af";
      fsType = "btrfs";
      options = [ "subvol=@rootfs" "noatime" "compress=zstd" "space_cache=v2" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/5a387e47-22ae-4e1d-81da-b9ac913a48af";
      fsType = "btrfs";
      options = [ "subvol=@home" "noatime" "compress=zstd" "space_cache=v2" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/5a387e47-22ae-4e1d-81da-b9ac913a48af";
      fsType = "btrfs";
      options = [ "subvol=@nix" "noatime" "compress=zstd" "space_cache=v2" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/5a387e47-22ae-4e1d-81da-b9ac913a48af";
      fsType = "btrfs";
      options = [ "subvol=@persist" "noatime" "compress=zstd" "space_cache=v2" ];
      neededForBoot = true;
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/5a387e47-22ae-4e1d-81da-b9ac913a48af";
      fsType = "btrfs";
      options = [ "subvol=@log" "noatime" "compress=zstd" "space_cache=v2" ];
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/24A9-14F0";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
